#!/usr/bin/env bash
set -euo pipefail

cleanup_date="2026-06-30"

branches=(
  "ai-patch-safety-guardrails"
  "archive-checkpoint"
  "checkpoint-15"
  "checkpoint-16"
  "checkpoint-17"
  "checkpoint-19"
  "checkpoint-20"
  "checkpoint-21"
  "checkpoint-22"
  "checkpoint-23"
  "checkpoint-24"
  "checkpoint-25"
  "checkpoint-26"
  "checkpoint-27"
  "checkpoint-28"
  "checkpoint-29"
  "checkpoint-30"
  "checkpoint-31"
  "checkpoint-32"
  "checkpoint-33"
  "checkpoint-34"
  "checkpoint-98386ccf"
  "codex/clarify-repo-access-in-environment"
  "codex/execute-codegraph-ai-executor-workflow"
  "codex/execute-codegraph-local-tooling"
  "cp12"
  "cp13"
  "lifecycle-checkpoint"
  "restore-apply-receipts"
  "restore-conflicts"
  "restore-delivery-2026-05-19"
  "restore-delivery-jobs"
  "restore-dispatch-decisions"
  "restore-dispatch-policy"
  "restore-exchange-linkage"
  "restore-import-records"
  "restore-intake-decisions"
  "restore-merge-decisions"
  "restore-outbox-items"
  "restore-received-items"
  "restore-routing-2026-05-19"
  "restore-rp"
  "restore-snapshots"
  "restore-state-transitions"
  "restore-transport-2026-05-19"
  "restore-transport-receipts-2026-05-19"
  "restore/adapter-registry-2026-05-19"
  "restore/audit-journal-2026-05-19"
  "restore/before-codegraph"
  "restore/capability-registry-2026-05-19"
  "restore/catalog-cli-2026-05-19"
  "restore/confidence-quality-2026-05-19"
  "restore/doctor-cli-2026-05-19"
  "restore/example-registry-2026-05-19"
  "restore/examples-2026-05-19"
  "restore/exchange-bundles-2026-05-19"
  "restore/federation-topology-2026-05-19"
  "restore/integrity-receipts-2026-05-19"
  "restore/lineage-validation-2026-05-19"
  "restore/manual-adapter-2026-05-19"
  "restore/node-identity-2026-05-19"
  "restore/playbooks-2026-05-19"
  "restore/profile-registry-2026-05-19"
  "restore/reconciliation-2026-05-19"
  "restore/record-schema-contracts-2026-05-19"
  "restore/retention-disposition-2026-05-19"
  "restore/review-decisions-2026-05-19"
  "restore/runtime-seed-2026-05-19"
  "restore/sharing-policy-2026-05-19"
  "restore/source-provenance-2026-05-19"
  "restore/workflow-fixed-2026-05-19"
  "spare"
  "spare10"
  "spare11"
  "spare2"
  "spare3"
  "spare4"
  "spare5"
  "spare6"
  "spare7"
  "spare8"
  "spare9"
)

git fetch --all --prune

for branch in "${branches[@]}"; do
  safe_branch="$(printf '%s' "$branch" | sed 's#[^A-Za-z0-9._-]#-#g')"
  tag="archive/${safe_branch}-${cleanup_date}"

  echo "Archiving origin/${branch} as ${tag}"
  if git rev-parse -q --verify "refs/tags/${tag}" >/dev/null; then
    echo "Archive tag already exists: ${tag}"
  else
    git tag "${tag}" "origin/${branch}"
    git push origin "${tag}"
  fi

  if git rev-parse -q --verify "refs/remotes/origin/${branch}" >/dev/null; then
    echo "Deleting remote branch origin/${branch}"
    git push origin --delete "${branch}"
  else
    echo "Remote branch already absent: origin/${branch}"
  fi
done
